# Generated by Django 4.1.1 on 2022-11-22 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='left',
        ),
    ]
