# Generated by Django 4.1.1 on 2022-11-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_quantity_product_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discountCode', models.CharField(max_length=25)),
                ('discountDescription', models.CharField(max_length=255)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=False)),
                ('discountPrcntAsDecimal', models.DecimalField(decimal_places=3, max_digits=3)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('-creationDate', 'discountCode'),
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='left',
        ),
    ]
