# Generated by Django 4.1.1 on 2022-11-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_discountcode_remove_product_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='left',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
