# Generated by Django 4.1.1 on 2022-11-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='slug',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='discountPrcntAsNmbr',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
